version: "3.3"

services:
  http-server:
    container_name: http-server
    image: node:16.17.0-buster
    restart: on-failure
    command: npx http-server /var/www -p 5000 -s
    volumes:
      - ./public:/var/www

  http-proxy:
    build: .
    container_name: http-proxy
    restart: on-failure
    environment:
      MODE: http-proxy-middleware
      TARGET: http://http-server:5000
      PORT: 7000
      MEMORY_USAGE_INTERVAL: 10000
    ports:
      - "7000:7000"

  loadtest:
    container_name: loadtest
    image: node:16.17.0-buster
    restart: on-failure
    command: bash -c 'while :; do curl -s -I -X GET http://http-proxy:7000/sample.png > /dev/null; done'
