version: "3.3"

services:
  http-proxy:
    build:
      context: .
      args:
        - NODE_VERSION
    container_name: http-proxy
    restart: on-failure
    environment:
      - MODE
      - MEMORY_USAGE_INTERVAL
      - HTTP_SERVER_PORT=5000
      - HTTP_PROXY_PORT=7000
    ports:
      - "7000:7000"

  loadtest:
    container_name: loadtest
    image: node:${NODE_VERSION}-buster
    restart: on-failure
    command: script -qefc "bash -c 'sleep 3; while :; do curl -s -I -X GET http://http-proxy:7000/sample.png > /dev/null; done'" /dev/null
    depends_on:
      - http-proxy
